#
# Awesome App Landing Page Config
#
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: 球路App # REQUIRED - Enter your app name
  ios_id: 1082206283 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: com.lee.cliplay # Optional - Enter Android app id like: com.example.app

  icon: http://ww2.sinaimg.cn/mw690/006p1Rrsgw1f6fvv09gxnj30e80e8dhw.jpg # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  screenshot: http://ww2.sinaimg.cn/mw690/006p1Rrsgw1f6fvv1flsmj30hs0vkjuf.jpg # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

#
# Marketing
#
marketing_header: 篮球动图专家 # Optional
marketing_desc: 超过37位顶级NBA球星的动图库，以动作分类，系统、全面。总计超过5000张动图，并持续增加和更新。同屏流畅显示大量动图，集成自动播放/暂停，极致欣赏体验。独创无级拖放，前后快慢，随心所欲，洞察每帧的动作细节。一键收藏，你的最爱一览无遗。支持离线使用，随时随地，方便球场模仿演练。存储空间不足时自动清除下载内容并允许手动清除，节省空间。

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github:
  facebook:
  twitter:
  pinterest:
  instagram:
  email:
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  weibo: http://weibo.com/u/5866649154

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
background_image: http://ww4.sinaimg.cn/mw690/006p1Rrsgw1f6fvgwwlkdj31kw11xdme.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: 球路App官方下载页面 # Optional - Enter your site title
description: 球路App iOS和Android版官方下载 # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
